name: InstaClone

options:
  deploymentTarget: 
    iOS: "13.0"

targets:
  InstaClone:
    platform: iOS
    type: application
    sources:
      - InstaClone
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "Bartosz-Raczka-Development.InstaClone"

  InstaCloneTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - InstaCloneTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "Bartosz-Raczka-Development.InstaClone"